### ISSUE TITLE
MbsuinoAP: Overwriting the WiFi data with blank characters

### ISSUE THREAD

**Issue by thenebu** [Zeppelin500/MBusino#11]
Apart from two or three stumbling blocks, the setup was very simple and Mbusino reports to the MQTT server. I'll have to make sure that I connect the mBus master in the next few days and read out real values.

I have noticed several things:
1. I entered the wrong MQTT password during AP setup. I then wanted to change it. I read the IP of the board from the router and accessed it in the browser. I entered the MQTT data correctly. I did not enter anything for WiFi as I did not want to make any changes here. However, this resulted in the board being kicked out of my WiFi and after a short time the AP was unblocked. I suspect that the SSID and WiFi PW were overwritten with empty characters. 
2. a little hint that you should only enter the IP (without https) for the mqtt server would be helpful.
3. my FritzBox shows the board as "ESP-6752EB" and not as the entered name "Mbusino". With other D1 mini boards the naming works.

**Comment by Zeppelin500** [comment]
1. Yes the Portal is very simple. You have to fill out everything or the variables will be overwrite. I have to declare this at the Portal.
2.  An IP is without http. By the way, http is not our protocol here, mqtt is the protocol. But you can use a address too, like test.mosquitto.org
The full address is MQTT://test.mosquitoo.org:1883 but you need only the short version.
3. Ok, i figure out how I can set the client name and bring it to the next version. In the old version without AP the client name was shown in my Fritzbox but now, I have the same problem.

**Comment by Zeppelin500** [comment]
point 1 and 3 are implemented

**Comment by Zeppelin500** [comment]
for point 2, hint in tutorial added. --> issue is closed
