### ISSUE TITLE
mqtt password exposed in plain text

### ISSUE THREAD

**Issue by markuspulch** [Zeppelin500/MBusino#16]
**Describe the bug**
mqtt password exposed in plain text in topic MBusino/settings/pswd.

**Expected behavior**
a password should never be actively exposed

**Additional context**
I guess it should be self explainatory that this behaviour is a no-go from a security perspective. I guess is was implemented for debugging purposes not nevertheless there should be at least an option to disable this behaviour.

**Comment by Zeppelin500** [comment]
You are right, was for debugging.
As I don't use authentication for my MQTT network,  no focus on this.
Next version will be without mqtt password.

**Comment by Zeppelin500** [comment]
hide MQTT Password in 0.9.8
