### ISSUE TITLE
Link for piggyback PCB may be incorrect, not the same board as shown

### ISSUE THREAD

**Issue by dirkvdb2** [Zeppelin500/MBusino#4]
"Das Shield ist ein mit Fritzing konstruiertes Board. Der M-Bus wird über einen aufsteckbaren M-Bus Master bereitgestellt. https://de.aliexpress.com/item/33008746192.html --> der Master!"

This link points to a different board with at least partielly different pinning (only two pins for MBUS.
I found offers on aliexpress to the correct board, eg.:
https://www.aliexpress.com/item/1005004664326197.html?spm=a2g0o.cart.0.0.140338dajc8E4F&mp=1

**Comment by Zeppelin500** [comment]
Yes, but you will receive a board with 6 pins. 
But If you receive a board with only two pins at the MBus side, it will work also. Every 3 pins are connected.

**Comment by Zeppelin500** [comment]
Add a hint at the readme
